# Generated by Django 4.1.1 on 2022-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Тип бумаги"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Формат"
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Документы",
                "verbose_name_plural": "Документы",
                "ordering": ["id"],
            },
        ),
    ]
